### ISSUE TITLE
Setup an env variable called SECRET_KEY.

### ISSUE THREAD

**Issue by ahheaSK** [chijioke-ibekwe/spring-security-jwt#1]
5. Setup an env variable called SECRET_KEY. This value will be used in signing and decoding your JWT.
How to add env variable  called SECRET_KEY? add new file or what?
I'm new spring boot

**Comment by ahheaSK** [comment]
Thank I got it new

**Comment by chijioke-ibekwe** [comment]
Hi @ahheaSK . I'm glad you're sorted
